stages:
  - maventry
  - androidtry

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend
    - mvn package

android-build: #another job to build android
  image: gjandres/android-ci      # this is a directive to DOCKER
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=pwd/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend
    - ./gradlewbuild
  artifacts:
    paths:
      - Android_test/app/build/outputs/

android-test:  #another job to test android
  image: gjandres/android-ci
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend
    - .gradlew test
